---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: supreme-waffle-alpha
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: silver-pancake
              image: hsmtkk/silver-pancake:latest
              imagePullPolicy: Always
              env:
                - name: USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: supreme-waffle
                      key: username
                - name: PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: supreme-waffle
                      key: password
                - name: HOSTNAME
                  value: supwaf-alpha.ddns.net
                - name: IP_ADDRESS
                  value: 20.89.107.128
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: supreme-waffle-bravo
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: silver-pancake
              image: hsmtkk/silver-pancake:latest
              imagePullPolicy: Always
              env:
                - name: USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: supreme-waffle
                      key: username
                - name: PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: supreme-waffle
                      key: password
                - name: HOSTNAME
                  value: supwaf-bravo.ddns.net
                - name: IP_ADDRESS
                  value: 20.89.107.128
          restartPolicy: OnFailure
